<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>_obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/obj/**;**/_tmp_obj/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
