<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Calibration2.ico</ApplicationIcon>
    <AssemblyName>BlueMax.KeyGen.UI</AssemblyName>
    <RootNamespace>BlueMax.KeyGen.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueMax.Infrastructure\BlueMax.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
  </ItemGroup>

</Project>
